### PR TITLE
Introduce more Squawk parameters

### PR DESCRIPTION
**Pull request by Agraphie**
The underlying Squawk CLI features many more parameters than the current action. This PR introduces multiple CI relevant parameters so it's easier to configure them when using this action.

It also simplifies the pattern and files usage into one Squawk call instead of two.

### CODE REVIEW

**Comment by chdsbd** [comment]
Here's a PR with the old version: https://github.com/recipeyak/recipeyak/pull/1485

Here's a PR with the new version: https://github.com/recipeyak/recipeyak/pull/1484

I think we need to adjust how we find files

**Comment by chdsbd** [comment]
Ohhhh, I think there was a regression introduced in a recent commit

**Comment by chdsbd** [comment]
I think we may want to revert https://github.com/sbdchd/squawk-action/commit/4828f43d811c5ba4f57161324446b44c0e7488a4

We can add proper pattern support inside the squawk project. That way we can fix this issue

**Comment by Agraphie** [comment]
Thanks for the tests. The problem is the leading or non-leading `./`. I've changed the command to account for both and it tested it with a repo. Can you recheck please? The drawback of the previous `compgen` solution is that it doesn't really do multi-path glob pattern, but only for one path.

Natively supporting a pattern i.e. a list of files including patterns would be nice though, then we can save one parameter here

**Comment by chdsbd** [comment]
@Agraphie Looks good! Thanks for the quick update!

**Pull request merged**
